baseurl = "https://roaringbitmap.org/"
author = "Daniel Lemire"
title = "Roaring Bitmaps"
languageCode = "en-us"
theme = "hugof"
enableRobotsTXT = true
SectionPagesMenu = ["main", "social"]

[params.image]
ImageURL = "roaring.jpg"
IconURL = "roaring.jpg"
ImageCredit = "Picture credit: tambako"

[params.meta]
description = "Roaring Bitmaps"
keywords = "open source, compression, java, go, c, c++"

[params.hero]
herotitle = "A better compressed bitset"
herodiscription = "Roaring bitmaps are compressed bitmaps. They can be hundreds of times faster."
heroquote = """>Use Roaring for bitmap compression whenever possible. Do not use other bitmap compression methods ([Wang et al., SIGMOD 2017](http://db.ucsd.edu/wp-content/uploads/2017/03/sidm338-wangA.pdf))"""
btnblue = "Grab one of our research papers"
btnblueurl = "https://arxiv.org/pdf/1603.06549.pdf"
btngreen = "Roaring Bitmaps on GitHub"
btngreenurl = "https://github.com/RoaringBitmap/"
[params.main]
contentOneTitle = "Widely used"
contentTwoTitle = "Portable"

contentOneBody = """Roaring is found in

* [Apache Lucene](http://lucene.apache.org/core/) and derivative systems such as Solr and [Elasticsearch](https://www.elastic.co),
* [Metamarkets' Druid](http://druid.io/),
* [Apache Spark](http://spark.apache.org),
* [Apache Hive](http://hive.apache.org),
* [Apache Tez](http://tez.apache.org),
* [Apache CarbonData](https://carbondata.apache.org),
* [Netflix Atlas](https://github.com/Netflix/atlas),
* [LinkedIn Pinot](https://github.com/linkedin/pinot/wiki),
* [OpenSearchServer](http://www.opensearchserver.com),
* [Cloud Torrent](https://github.com/jpillora/cloud-torrent),
* [Whoosh](https://pypi.python.org/pypi/Whoosh/),
* [InfluxDB](https://www.influxdata.com),
* [Pilosa](https://www.pilosa.com/),
* [Bleve](http://www.blevesearch.com),
* [Microsoft Visual Studio Team Services (VSTS)](https://www.visualstudio.com/team-services/),
* [Intel's Optimized Analytics Package (OAP)](https://github.com/Intel-bigdata/OAP),
* [Tablesaw](https://github.com/jtablesaw/tablesaw),
* [Jive Miru](https://github.com/jivesoftware/miru),
* [Gaffer](https://github.com/gchq/Gaffer),
* [Apache Hivemall](http://hivemall.incubator.apache.org),
* eBay's [Apache Kylin](http://kylin.io). """

contentTwoBody = """There are freely available software libraries providing Roaring bitmaps in almost all the popular programming languages:

* [Java](https://github.com/lemire/RoaringBitmap/),
* [C, C++](https://github.com/RoaringBitmap/CRoaring),
* [Go](https://github.com/RoaringBitmap/roaring),
* [C#](https://github.com/RogueException/CRoaring.Net),
* [Rust](https://github.com/saulius/croaring-rs),
* [Python](https://github.com/Ezibenroc/PyRoaringBitMap),
* [D](https://github.com/yuce/droaring),
* ...

There is a serialized [format specification](https://github.com/RoaringBitmap/RoaringFormatSpec/) for interoperability between implementations."""


[params.footer]
emailtext = "Get in touch"
email = "lemire@gmail.com"
[[menu.main]]
name = "About"
url = "/about"

[[menu.main]]
name = "Software"
url = "/software"

[[menu.main]]
name = "Publications"
url = "/publications"

[[menu.main]]
name = "Talks"
url = "/talks"


[[menu.social]]
name = "Google Groups"
url = "https://groups.google.com/forum/#!forum/roaring-bitmaps"

[[menu.social]]
name = "Github"
url = "http://github.com/RoaringBitmap"
